dataset:
  batch_size: 32
  max_num_anchor_features: 0
  max_num_objects: 7
  max_num_other_objects: 5
  max_num_rearrange_features: 0
  max_num_shape_parameters: 5
  use_structure_frame: true
  num_pts: 1024
  num_workers: 4
  pin_memory: true
device: 0

model:
  encoder_activation: relu
  encoder_dropout: 0.0
  encoder_hidden_dim: 512
  encoder_num_layers: 8
  ignore_rgb: true
  name: structformer
  num_attention_heads: 8
  object_dropout: 0.1
  structure_dropout: 0.5
  theta_loss_divide: 3
obj_xytheta_relative: false
random_seed: 1
save_best_model: true
save_model: true
training:
  l2: 0.0001
  learning_rate: 0.0001
  lr_restart: 3000
  max_epochs: 200
  warmup: 10
