experiment_dir: ../../experiments/${env:DATETIME}

dataset:
  dirs:
    - /home/weiyu/data_drive/data_new_objects/examples_line_new_objects/result
  index_dirs:
    - index_42k
  vocab_dir: /home/weiyu/data_drive/data_new_objects/type_vocabs_coarse.json