random_seed: 1
device: 0

obj_xytheta_relative: False
save_model: True
save_best_model: True

dataset:
  batch_size: 128
  max_num_shape_parameters: 5
  max_num_objects: 7
  max_num_other_objects: 5
  max_num_rearrange_features: 1
  max_num_anchor_features: 3
  num_pts: 1024
  num_workers: 64
  pin_memory: True
  use_structure_frame: True
  filter:
    - "bottom"
    - "right"

model:
  name: utilityformer
  model_dim: 256
  utility_vector: "avg_pool"
  pretrained_model: "model/24-12-09"
  obj_selection:
    num_attention_heads: 8
    encoder_hidden_dim: 128
    encoder_dropout: 0.2
    encoder_activation: gelu
    encoder_num_layers: 6
    use_focal_loss: False
    focal_loss_gamma: 2
    model_dim: 256

  pos_generation:
    num_attention_heads: 8
    encoder_hidden_dim: 512
    encoder_dropout: 0.1
    encoder_activation: gelu
    encoder_num_layers: 8
    structure_dropout: 0.2
    object_dropout: 0.1
    theta_loss_divide: 3
    ignore_rgb: True
    model_dim: 256

training:
  learning_rate: 0.0001
  max_epochs: 30
  l2: 0.0001
  lr_restart: 3000
  warmup: 10

inference:
  use_utility_vector: True
  beam_size: 3
  max_scene_decodes: 1
  visualize: True
  visualize_action_sequence: False
  inference_visualization_dir: 'visualize'